// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/heavydash/my-avatars-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	uuid "github.com/google/uuid"
)

// AvatarUseCase is an autogenerated mock type for the AvatarUseCase type
type AvatarUseCase struct {
	mock.Mock
}

// DeleteAvatar provides a mock function with given fields: ctx, id
func (_m *AvatarUseCase) DeleteAvatar(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AvatarUseCase) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDWithOptions provides a mock function with given fields: ctx, id, size, format
func (_m *AvatarUseCase) GetByIDWithOptions(ctx context.Context, id uuid.UUID, size string, format string) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id, size, format)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithOptions")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*domain.Avatar, error)); ok {
		return rf(ctx, id, size, format)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *domain.Avatar); ok {
		r0 = rf(ctx, id, size, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, size, format)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *AvatarUseCase) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadAvatar provides a mock function with given fields: ctx, userID, file, header
func (_m *AvatarUseCase) UploadAvatar(ctx context.Context, userID uuid.UUID, file multipart.File, header *multipart.FileHeader) (*domain.Avatar, error) {
	ret := _m.Called(ctx, userID, file, header)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, multipart.File, *multipart.FileHeader) (*domain.Avatar, error)); ok {
		return rf(ctx, userID, file, header)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, multipart.File, *multipart.FileHeader) *domain.Avatar); ok {
		r0 = rf(ctx, userID, file, header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, multipart.File, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, userID, file, header)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAvatarUseCase creates a new instance of AvatarUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAvatarUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AvatarUseCase {
	mock := &AvatarUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
