apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: gophprofile
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migrate
          image: gophprofile/server:latest
          imagePullPolicy: Never
          command:
            - sh
            - -c
            - |
              echo "Running migrations..."
              goose -dir /home/appuser/migrations postgres "$DB_DSN" up
              echo "Migrations completed..."
          envFrom:
            - secretRef:
                name: avatar-secrets
      restartPolicy: Never