apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gophprofile
data:
  POSTGRES_DB: avatars
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gophprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gophprofile
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
