apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: avatar-server-role
  namespace: gophprofile
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]