apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: avatar-server-rolebinding
  namespace: gophprofile
subjects:
  - kind: ServiceAccount
    name: avatar-server-sa
    namespace: gophprofile
roleRef:
  kind: Role
  name: avatar-server-role
  apiGroup: rbac.authorization.k8s.io